### ISSUE TITLE
Undefined `a`

### ISSUE THREAD

**Issue by dcgerard** [maryclare/gnorm#1]
I think `a` should be `alpha` in

https://github.com/maryclare/gnorm/blob/master/R/gnorm.R#L17
https://github.com/maryclare/gnorm/blob/master/R/gnorm.R#L20

**Comment by maryclare** [comment]
lol you are right I texted you, I should keep my personal in construction
repositories private!

**Comment by maryclare** [comment]
You are correct! I caught that this this afternoon but hadn't updated it yet.
